---
title: "R Notebook"
output:
  html_notebook:
    toc: yes
    toc_float: yes
  html_document:
    df_print: paged
    toc: yes
    toc_float: yes
---

```{r}
library(gridExtra)
library(tidyverse)
library(lattice)
library(GGally)
library(here)
library(grid)
```

# Data Overview

```{r}
eleicoes_data <- readr::read_csv(
  here::here('data/eleicoes_2006_e_2010.csv'), 
  local=readr::locale("br"),
  col_types = cols(
    ano = col_integer(),
    sequencial_candidato = col_character(),
    quantidade_doacoes = col_integer(),
    quantidade_doadores = col_integer(),
    total_receita = col_double(),
    media_receita = col_double(),
    recursos_de_outros_candidatos.comites = col_double(),
    recursos_de_pessoas_fisicas = col_double(),
    recursos_de_pessoas_juridicas = col_double(),
    recursos_proprios = col_double(),
    `recursos_de_partido_politico` = col_double(),
    quantidade_despesas = col_integer(),
    quantidade_fornecedores = col_integer(),
    total_despesa = col_double(),
    media_despesa = col_double(),
    votos = col_integer(),
    .default = col_character()))

eleicoes_data %>% 
  mutate(uf = as.factor(uf),
         nome = as.factor(nome),
         sexo = as.factor(sexo),
         grau = as.factor(grau),
         nome = as.factor(nome),
         cargo = as.factor(cargo),
         partido = as.factor(partido),
         ocupacao = as.factor(ocupacao),
         estado_civil = as.factor(estado_civil),
         sequencial_candidato = as.numeric(sequencial_candidato)) -> eleicoes_data

eleicoes_data %>% 
  glimpse()
```

```{r}
eleicoes_data %>%
  filter(ano == 2006) %>%
  group_by(partido) %>%
  summarize(n = n()) %>%
  ggplot(aes(reorder(partido,n), n)) +
  geom_bar(stat = "identity") + 
  theme(axis.text.x = element_text(angle = 90,
                                   hjust = 1)) +
  scale_y_continuous(limits = c(0,350)) +
  labs(x="Political Party",
       title="2006 elections",
       y="Absolute Frequency") -> p1

eleicoes_data %>%
  filter(ano == 2010) %>%
  group_by(partido) %>%
  summarize(n = n()) %>%
  ggplot(aes(reorder(partido,n), n)) +
  geom_bar(stat = "identity") + 
  theme(axis.text.x = element_text(angle = 90,
                                   hjust = 1)) +
  scale_y_continuous(limits = c(0,350)) +
  labs(x="Political Party",
       title="2010 elections",
       y="Absolute Frequency") -> p2

grid.arrange(p1, p2, ncol=1)
```

```{r}
eleicoes_data %>%
  ggplot(aes(total_receita)) +
  geom_histogram(bins = 30) +
  labs(x="Total Revenue",
       y="Absolute Frequency") +
  facet_grid(. ~ ano)
```

```{r}
eleicoes_data %>%
  ggplot(aes(media_receita)) +
  geom_histogram(bins = 30) +
  labs(x="Mean Revenue",
       y="Absolute Frequency") +
  facet_grid(. ~ ano)
```

```{r}
eleicoes_data %>%
  ggplot(aes(total_despesa)) +
  geom_histogram(bins = 30) +
  labs(x="Total Expenditure",
       y="Absolute Frequency") +
  facet_grid(. ~ ano)
```

```{r}
eleicoes_data %>%
  ggplot(aes(media_despesa)) +
  geom_histogram(bins = 30) +
  labs(x="Mean Expenditure",
       y="Absolute Frequency") +
  facet_grid(. ~ ano)
```

```{r}
eleicoes_data %>%
  ggplot(aes(recursos_proprios)) +
  geom_histogram(bins = 30) +
  labs(x="Total Revenue",
       y="Absolute Frequency") +
  facet_grid(. ~ ano)
``` 

```{r}
eleicoes_data %>%
  mutate(ano = as.factor(ano)) %>%
  group_by(estado_civil, ano) %>%
  summarize(n = n()) %>%
  ggplot(aes(reorder(estado_civil,n), n,
             fill= ano)) +
  geom_bar(stat = "identity",
           position = position_dodge(width = 0.5)) + 
  labs(x="Marital status", 
       y="Absolute Frequency") +
  guides(fill = guide_legend(title = "year")) +
  coord_flip()
```

```{r}
eleicoes_data %>%
  mutate(ano = as.factor(ano)) %>%
  group_by(grau, ano) %>%
  summarize(n = n()) %>%
  ggplot(aes(reorder(grau,n), n,
             fill= ano)) +
  geom_bar(stat = "identity",
           position = position_dodge(width = 0.5)) + 
  labs(x="Education level", 
       y="Absolute Frequency") +
  guides(fill = guide_legend(title = "year")) +
  coord_flip()
```

```{r}
eleicoes_data %>%
  group_by(sexo, ano) %>%
  summarize(n = n()) %>%
  ggplot(aes(reorder(sexo,n), n)) +
  geom_bar(stat = "identity") + 
  labs(x="Gender", 
       y="Absolute Frequency") +
  facet_grid(. ~ano)
```

```{r}
require(GGally)

eleicoes_data %>% 
  filter(ano == 2006) %>%
  select(-partido,
         -uf,-nome,
         -estado_civil,
         -ocupacao,-ano,
         -cargo,-grau,-sexo) %>%
  na.omit() %>%
  ggcorr(palette = "RdBu",
         color = "grey50",
         label = TRUE, hjust = 1,
         label_size = 3, size = 4,
         nbreaks = 5, layout.exp = 7) +
  ggtitle("Correlation plot for 2006 elections")
```

```{r}
require(GGally)

eleicoes_data %>% 
  filter(ano == 2010) %>%
  select(-partido,
         -uf,-nome,
         -estado_civil,
         -ocupacao,-ano,
         -cargo,-grau,-sexo) %>%
  na.omit() %>%
  ggcorr(palette = "RdBu",
         color = "grey50",
         label = TRUE, hjust = 1,
         label_size = 3, size = 4,
         nbreaks = 5, layout.exp = 7) +
  ggtitle("Correlation plot for 2010 elections")
```

## Splitting Data for Cross Validation (2006)

```{r}
eleicoes_data %>% ## Put numeric predictor variables on same scale 
   filter(ano == 2006) %>%
   mutate_at(.vars = vars(quantidade_doacoes,
                          quantidade_doadores,
                          total_receita,
                          media_receita,
                          sequencial_candidato,
                          recursos_de_outros_candidatos.comites,
                          recursos_de_pessoas_fisicas,
                          recursos_de_pessoas_juridicas,
                          recursos_proprios,
                          recursos_de_partido_politico,
                          quantidade_despesas,
                          quantidade_fornecedores,
                          total_despesa,
                          media_despesa),
             .funs = funs(as.numeric(scale(.)))) -> data_scaled

data_scaled %>%
  glimpse()
```

```{r}
set.seed(101) # We set the set for reason of reproducibility

## Adding surrogate key to dataframe
data_scaled$id <- 1:nrow(data_scaled)

data_scaled %>% 
  dplyr::sample_frac(.7) -> training_data

training_data %>% 
  glimpse()
```

```{r}
dplyr::anti_join(data_scaled, 
                 training_data, 
                 by = 'id') -> testing_data
testing_data %>% 
  glimpse()
```

# 2006, All predictors

* **cargo** is a one level factor and for that reason we must refrain from using it in our regression.

```{r}
mod <- lm(votos ~ total_receita * total_despesa + partido * estado_civil + 
                  media_despesa * grau + recursos_de_partido_politico * partido + 
                  quantidade_fornecedores * partido + media_despesa * partido +
                  recursos_de_outros_candidatos.comites * ocupacao +
                  uf * total_despesa + total_receita * partido + 
                  total_despesa * partido + sexo * uf,
          data = training_data)
broom::glance(mod)
```
