---
title: "Analysis with Regularization on Brazilian elections"
subtitle: "Predictive analysis with regularization and Hyperparameter tuning on data about Brazilian elections"
author: "José Benardi de Souza Nunes"
output:
  html_notebook:
    toc: yes
    toc_float: yes
  html_document:
    df_print: paged
    toc: yes
    toc_float: yes
---


```{r}
library(dataPreparation)
library(tidyverse)
library(caret)
library(here)
```

# Load Data

```{r}
data <- readr::read_csv(
  here::here('data/train.csv'), 
  progress = FALSE,
  local=readr::locale("br"),
  col_types = cols(
    ano = col_integer(),
    sequencial_candidato = col_character(),
    quantidade_doacoes = col_integer(),
    quantidade_doadores = col_integer(),
    total_receita = col_double(),
    media_receita = col_double(),
    recursos_de_outros_candidatos.comites = col_double(),
    recursos_de_pessoas_fisicas = col_double(),
    recursos_de_pessoas_juridicas = col_double(),
    recursos_proprios = col_double(),
    `recursos_de_partido_politico` = col_double(),
    quantidade_despesas = col_integer(),
    quantidade_fornecedores = col_integer(),
    total_despesa = col_double(),
    media_despesa = col_double(),
    votos = col_integer(),
    .default = col_character())) %>%
  mutate(sequencial_candidato = as.numeric(sequencial_candidato),
         estado_civil = as.factor(estado_civil),
         ocupacao = as.factor(ocupacao),
         partido = as.factor(partido),
         grau = as.factor(grau),
         sexo = as.factor(sexo),
         uf = as.factor(uf))

# Adding surrogate key to dataframe
data$id <- 1:nrow(data)

data %>% 
  glimpse()
```

```{r}
data %>%
  map_df(function(x) sum(is.na(x))) %>%
  gather(feature, num_nulls) %>%
  arrange(desc(num_nulls))
```

```{r}
data_test <- readr::read_csv(
  here::here('data/test.csv'), 
  progress = FALSE,
  local=readr::locale("br"),
  col_types = cols(
    ano = col_integer(),
    sequencial_candidato = col_character(),
    quantidade_doacoes = col_integer(),
    quantidade_doadores = col_integer(),
    total_receita = col_double(),
    media_receita = col_double(),
    recursos_de_outros_candidatos.comites = col_double(),
    recursos_de_pessoas_fisicas = col_double(),
    recursos_de_pessoas_juridicas = col_double(),
    recursos_proprios = col_double(),
    `recursos_de_partido_politico` = col_double(),
    quantidade_despesas = col_integer(),
    quantidade_fornecedores = col_integer(),
    total_despesa = col_double(),
    media_despesa = col_double(),
    .default = col_character())) %>%
  mutate(sequencial_candidato = as.numeric(sequencial_candidato))

data_test %>% 
  glimpse()

```

```{r}
data_test %>%
  map_df(function(x) sum(is.na(x))) %>%
  gather(feature, num_nulls) %>%
  arrange(desc(num_nulls))
```


<!-- ```{r} -->
<!-- data_test %>% -->
<!--   mutate(recursos_de_pessoas_juridicas = ifelse(is.na(recursos_de_pessoas_juridicas), -->
<!--                                                mean(recursos_de_pessoas_juridicas, na.rm=TRUE), -->
<!--                                                recursos_de_pessoas_juridicas), -->
<!--          recursos_de_partido_politico = ifelse(is.na(recursos_de_partido_politico), -->
<!--                                                mean(recursos_de_partido_politico, na.rm=TRUE), -->
<!--                                                recursos_de_partido_politico), -->
<!--          recursos_proprios = ifelse(is.na(recursos_proprios), -->
<!--                                                mean(recursos_proprios, na.rm=TRUE), -->
<!--                                                recursos_proprios), -->
<!--          recursos_de_outros_candidatos.comites = ifelse(is.na(recursos_de_outros_candidatos.comites), -->
<!--                                                mean(recursos_de_outros_candidatos.comites, na.rm=TRUE), -->
<!--                                                recursos_de_outros_candidatos.comites), -->
<!--          recursos_de_pessoas_fisicas = ifelse(is.na(recursos_de_pessoas_fisicas), -->
<!--                                                mean(recursos_de_pessoas_fisicas, na.rm=TRUE), -->
<!--                                                recursos_de_pessoas_fisicas)) -> data_test -->

<!-- ``` -->

```{r results='asis'}
encoding <- build_encoding(dataSet = data,
                           cols = c("uf","sexo","grau","ocupacao",
                                    "partido","estado_civil"),
                           verbose = F)

data <- one_hot_encoder(dataSet = data,
                           encoding = encoding,
                           drop = TRUE,
                           verbose = F)

cat("#### Data Shape",
    "\n##### Observations: ",nrow(data),
    "\n##### Variables: ",ncol(data))
```

```{r results='asis'}
data_test <- one_hot_encoder(dataSet = data_test,
                           encoding = encoding,
                           drop = TRUE,
                           verbose = F)

cat("#### Test Data Shape",
    "\n##### Observations: ",nrow(data_test),
    "\n##### Variables: ",ncol(data_test))
```

<!-- ```{r results='asis'} -->
<!-- set.seed(11) # We set the set for reason of reproducibility -->

<!-- data %>% -->
<!--   dplyr::sample_frac(.6) -> data_train -->

<!-- encoding <- build_encoding(dataSet = data_train, -->
<!--                            cols = c("uf","sexo","grau","ocupacao", -->
<!--                                     "partido","estado_civil"), -->
<!--                            verbose = F) -->

<!-- data_train <- one_hot_encoder(dataSet = data_train, -->
<!--                            encoding = encoding, -->
<!--                            drop = TRUE, -->
<!--                            verbose = F) -->

<!-- cat("#### Train Data ", -->
<!--     "\n##### Observations: ",nrow(data_train), -->
<!--     "\n##### Variables: ",ncol(data_train)) -->
<!-- ``` -->

<!-- <br> -->

<!-- ```{r results='asis'} -->
<!-- set.seed(11) # We set the set for reason of reproducibility -->

<!-- dplyr::anti_join(data, -->
<!--                  data_train, -->
<!--                  by = 'id') -> intermediate_data -->

<!-- intermediate_data %>% -->
<!--   dplyr::sample_frac(.5) -> data_test -->

<!-- data_test <- one_hot_encoder(dataSet = data_test, -->
<!--                            encoding = encoding, -->
<!--                            drop = TRUE, -->
<!--                            verbose = F) -->

<!-- cat("#### Test Data ", -->
<!--     "\n##### Observations: ",nrow(data_test), -->
<!--     "\n##### Variables: ",ncol(data_test)) -->
<!-- ``` -->

<!-- ```{r results='asis'} -->
<!-- set.seed(11) # We set the set for reason of reproducibility -->

<!-- dplyr::anti_join(intermediate_data, -->
<!--                  data_test, -->
<!--                  by = 'id') -> data_validate -->


<!-- data_validate <- one_hot_encoder(dataSet = data_validate, -->
<!--                            encoding = encoding, -->
<!--                            drop = TRUE, -->
<!--                            verbose = F) -->
<!-- rm(intermediate_data) -->

<!-- cat("#### Validate Data ", -->
<!--     "\n##### Observations: ",nrow(data_validate), -->
<!--     "\n##### Variables: ",ncol(data_validate)) -->
<!-- ``` -->

# Ridge

```{r}
data %>%
  nearZeroVar(saveMetrics = TRUE) %>%
  tibble::rownames_to_column("variable") %>%
  filter(nzv == T) %>% 
  pull(variable) -> near_zero_vars
```

```{r}
# 
# model.cv <- train(mpg ~ ., 
#                data = mtcars,
#                method = "lasso",
#                trControl = fitControl)
# 

# boot", "boot632", "cv", "repeatedcv", "LOOCV", "LGOCV"
```


```{r}
lambdaGrid <- expand.grid(lambda = 10^seq(10, -2, length=100))

fitControl <- trainControl(## 10-fold CV
                           method = "repeatedcv", 
                           number = 10)

data %>%
  select(-one_of(near_zero_vars)) %>%
  select(-ano,-id, -nome) %>%
  train(votos ~ .,
        data = .,
        method = "ridge",
        na.action = na.omit,
        tuneGrid = lambdaGrid,
        trControl = fitControl,
        preProcess = c('scale', 'center')) -> model.ridge

model.ridge
```

```{r}
model.ridge %>%
  varImp() %>%
  ggplot()
```
```{r}
fractionGrid <- expand.grid(fraction = seq(1, 1e-2, length=100))

data %>%
  select(-one_of(near_zero_vars)) %>%
  select(-ano,-id, -nome) %>%
  train(votos ~ .,
        data = .,
        method = "lasso",
        na.action = na.omit,
        tuneGrid = fractionGrid,
        trControl = fitControl,
        preProcess = c('scale', 'center')) -> model.lasso

model.lasso
```

```{r}
model.lasso %>%
  varImp() %>%
  ggplot()
```

```{r}
neighborsGrid <- expand.grid(k = seq(1, 100, length=100))

data %>%
  select(-one_of(near_zero_vars)) %>%
  select(-ano,-id, -nome) %>%
  train(votos ~ .,
        data = .,
        method = "knn",
        na.action = na.omit,
        tuneGrid = neighborsGrid,
        trControl = fitControl,
        preProcess = c('scale', 'center')) -> model.knn

model.knn
```

```{r}
model.knn %>%
  varImp() %>%
  ggplot()
```

```{r}
data %>%
  select(-one_of(near_zero_vars)) %>%
  select(-ano,-id, -nome) %>%
  train(votos ~ .,
        data = .,
        method = "knn",
        na.action = na.omit,
        tuneGrid = data.frame(k = 12),
        trControl = trainControl(method="none"),
        preProcess = c('scale', 'center')) -> model.knn.best

model.knn.best
```

```{r}
control <- trainControl(method="cv",
                        number=10,
                        search="grid")
set.seed(113)

tunegrid <- expand.grid(.mtry=c(1:50))

data %>%
  select(-one_of(near_zero_vars)) %>%
  select(-ano,-id, -nome) %>%
  train(votos ~.,
        data=.,
        method="rf",
        trControl=control,
        tuneGrid=tunegrid,
        na.action = na.omit,
        preProcess = c('scale', 'center')) -> model.rf

model.rf
```



```{r}
data_test %>% 
  mutate(sequencial_candidato = as.character(sequencial_candidato)) %>%
  pull(sequencial_candidato) -> id_column

predict(model.knn.best, data_test) -> predictions

data.frame(ID = id_column,
           votos = predictions) -> submissão

submissão %>%
  glimpse()
```

```{r}
write_csv(submissão,
          here::here('data/submission.csv'))
```

